---
  
- hosts: ROUTERS
  gather_facts: false
  connection: local
 

  tasks:
    - name: configure interface settings
      ios_l3_interface:
              name: GigabitEthernet0/2 
              ipv4: 192.168.5.5/24
